services:
  postgres:
    image: postgres:15
    container_name: test_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      - MSSQL_SA_PASSWORD=StrongPasswo0RD!
      - ACCEPT_EULA=Y
    volumes:
      - ./mssql/init/dbupgrade.sql:/scripts/dbupgrade.sql
    command:
      - /bin/bash
      - -c 
      - |
        # Start SQL Server in background
        /opt/mssql/bin/sqlservr &
      
        # Wait for SQL Server to be ready
        sleep 10
       
        # Execute initialization script with error handling
        if [ -f "/scripts/dbupgrade.sql" ]; then
        echo "Executing initialization script..."
        /opt/mssql-tools18/bin/sqlcmd \
          -S localhost \
          -U SA \
          -P 'StrongPasswo0RD!' \
          -d master \
          -i /scripts/dbupgrade.sql \
          -N -C \
          -b -o /tmp/sqlcmd.log
        cat /tmp/sqlcmd.log
        else
          echo "Error: Initialization script not found at /scripts/dbupgrade.sql"
          exit 1
        fi
      
        # Keep container running
        wait
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: test_oracle
    environment:
      ORACLE_PWD: "OraclePass123"
    ports:
      - "1521:1521"
    volumes:
      - ./oracle/init:/opt/oracle/scripts/startup
