BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR2(50),
        email VARCHAR2(100)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    INSERT INTO users (username, email)
    VALUES ('oracle_user', 'oracle@example.com');
    COMMIT;
END;
/

SELECT * FROM users;
